// Generated by scripts/generate-region-routes.mjs. Runs in cpt1 (Cape Town, South Africa) when NAVPROBE_REGIONS includes it.
import { runScenarioRequest } from '@/lib/run-handler'

export const runtime = 'nodejs'
export const maxDuration = 300

export function POST(req: Request) {
  return runScenarioRequest(req, 'cpt1')
}
