// Generated by scripts/generate-region-routes.mjs. Runs in hnd1 (Tokyo, Japan) when NAVPROBE_REGIONS includes it.
import { runScenarioRequest } from '@/lib/run-handler'

export const runtime = 'nodejs'
export const maxDuration = 300

export function POST(req: Request) {
  return runScenarioRequest(req, 'hnd1')
}
