// Generated by scripts/generate-region-routes.mjs. Runs in icn1 (Seoul, South Korea) when NAVPROBE_REGIONS includes it.
import { runScenarioRequest } from '@/lib/run-handler'

export const runtime = 'nodejs'
export const maxDuration = 300

export function POST(req: Request) {
  return runScenarioRequest(req, 'icn1')
}
