// Generated by scripts/generate-region-routes.mjs. Runs in gru1 (São Paulo, Brazil) when NAVPROBE_REGIONS includes it.
import { runScenarioRequest } from '@/lib/run-handler'

export const runtime = 'nodejs'
export const maxDuration = 300

export function POST(req: Request) {
  return runScenarioRequest(req, 'gru1')
}
