// Generated by scripts/generate-region-routes.mjs. Runs in cdg1 (Paris, France) when NAVPROBE_REGIONS includes it.
import { runScenarioRequest } from '@/lib/run-handler'

export const runtime = 'nodejs'
export const maxDuration = 300

export function POST(req: Request) {
  return runScenarioRequest(req, 'cdg1')
}
